### ISSUE TITLE
Quacking delay may be infinite

### ISSUE THREAD

**Issue by sameer-s** [joeysteele2001/quack#1]
The time between quacks is given by `-rate * Math.log(Math.random());`. As `Math.random()` generates values in the range $[0,1)$, this means that the value may be equal to `-rate * Math.log(0)` which will equal `Infinity` for any positive `rate`.

Additionally, even with arbitrary small values (e.g. `Math.random() = 1e-100`), the delay may take on the order of hours to execute. Ideally, users would be able to provide their own random distribution for the delay (rather than the currently built-in exponential distribution with $\lambda=1$) and accordingly provide an upper bound on the delay.

**Comment by joeysteele2001** [comment]
Point taken with the cap on random values. For *art*, the maximum duration between quacks is now 30 minutes.

As for setting one's own random distribution, that can be done in the future, but would detract from the simplicity. *Minimalism* and all that. I'll consider it though!

**Comment by sameer-s** [comment]
LGTM!
